spring.application.name=p2p
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
# Logging
logging.level.root=INFO
logging.level.com.finovago.p2p=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [correlationId=%X{correlationId}] - %msg%n

#swagger doc
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.urls-primary-name=customer-api
springdoc.swagger-ui.urls[0].name=customer-api
springdoc.swagger-ui.urls[0].url=/api-docs/customer-api
springdoc.swagger-ui.urls[1].name=admin-api
springdoc.swagger-ui.urls[1].url=/api-docs/admin-api
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha


