# Logging - Production
logging.level.root=WARN
logging.level.com.finovago.p2p=INFO
logging.level.org.springframework.web=WARN
logging.level.org.springframework.web.context.request.async=WARN

logging.file.name=logs/p2p.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [correlationId=%X{correlationId}] - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [correlationId=%X{correlationId}] - %msg%n

# Connection Pool
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5

spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Swagger/OpenAPI disabled in production
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

loki.username=${GRAFANA_LOKI_USER}
loki.password=${GRAFANA_LOKI_TOKEN}

