spring.application.name=p2p
# For production, set via environment: export SPRING_PROFILES_ACTIVE=prod
spring.profiles.active=dev

# Logging
logging.level.root=INFO
logging.level.com.finovago.p2p=DEBUG
logging.level.org.springframework.web=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [correlationId=%X{correlationId}] - %msg%n
