CREATE TABLE gift_card_hold (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gift_card_id  BIGINT NOT NULL REFERENCES gift_card(id),
    merchant_id   BIGINT NOT NULL REFERENCES merchants(id),
    amount        DOUBLE PRECISION NOT NULL CHECK (amount > 0),
    status        VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'CAPTURED', 'RELEASED', 'EXPIRED')),
    created_at    TIMESTAMP NOT NULL DEFAULT now(),
    expires_at    TIMESTAMP NOT NULL
);

-- Fast lookup for reserve's "sum of pending holds for this gift card" query,
-- and for the scheduler's "find expired pending holds" sweep.
CREATE INDEX idx_gift_card_hold_giftcard_status ON gift_card_hold (gift_card_id, status);

-- Fast lookup for the merchant-scoped by-id check used by capture/release.
CREATE INDEX idx_gift_card_hold_merchant_id ON gift_card_hold (merchant_id, id);

-- Supports the scheduler's periodic sweep for expiry candidates.
CREATE INDEX idx_gift_card_hold_status_expires_at ON gift_card_hold (status, expires_at)
    WHERE status = 'PENDING';
