CREATE TABLE idempotency_key (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id       BIGINT NOT NULL REFERENCES merchants(id),
    idempotency_key   VARCHAR(255) NOT NULL,
    request_hash      VARCHAR(64) NOT NULL,
    status            VARCHAR(20) NOT NULL CHECK (status IN ('IN_PROGRESS', 'COMPLETED')),
    response_status   VARCHAR(20),
    deducted_amount   DOUBLE PRECISION,
    remaining_balance DOUBLE PRECISION,
    remaining_to_pay  DOUBLE PRECISION,
    created_at        TIMESTAMP NOT NULL DEFAULT now(),
    expires_at        TIMESTAMP NOT NULL
);

-- Enforces one outcome per (merchant, key): also the concurrency guard that makes the
-- claim-row insert in IdempotencyKeyService race-safe under parallel duplicate requests.
CREATE UNIQUE INDEX idx_idempotency_key_merchant_key ON idempotency_key (merchant_id, idempotency_key);

-- Supports the scheduler's periodic sweep for expired entries.
CREATE INDEX idx_idempotency_key_expires_at ON idempotency_key (expires_at);
