CREATE TABLE gift_card_ledger (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gift_card_id  BIGINT NOT NULL REFERENCES gift_card(id),
    merchant_id   BIGINT NOT NULL REFERENCES merchants(id),
    entry_type    VARCHAR(20) NOT NULL CHECK (entry_type IN ('CREATION', 'REDEMPTION', 'HOLD_PLACED', 'HOLD_CAPTURED', 'HOLD_RELEASED')),
    amount        DOUBLE PRECISION NOT NULL,
    balance_after DOUBLE PRECISION NOT NULL,
    reference_id  BIGINT,
    created_at    TIMESTAMP NOT NULL DEFAULT now()
);

-- Fast lookup for a card's history, ordered chronologically.
CREATE INDEX idx_gift_card_ledger_giftcard_created_at ON gift_card_ledger (gift_card_id, created_at);

-- Fast lookup for a merchant-wide ledger listing.
CREATE INDEX idx_gift_card_ledger_merchant_id ON gift_card_ledger (merchant_id);
