-- gift_card_ledger is an append-only audit trail that grows without bound. Partitioning by year
-- makes future retention/archival (DETACH PARTITION + export + drop) an instant metadata operation
-- instead of a slow DELETE, and keeps per-partition indexes/vacuum small as the table grows.
-- Yearly (not monthly) because the actual retention policy this is meant to support is expressed in
-- years ("keep 2-3 years"), and the current query patterns don't filter by date range - a finer grain
-- would only add catalog/index overhead without a matching benefit.
--
-- Postgres cannot ALTER TABLE an existing table into a partitioned one, so this does a
-- create-copy-swap, all within this one transactional migration.

CREATE TABLE gift_card_ledger_new (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    gift_card_id  BIGINT NOT NULL REFERENCES gift_card(id),
    merchant_id   BIGINT NOT NULL REFERENCES merchants(id),
    entry_type    VARCHAR(20) NOT NULL CHECK (entry_type IN ('CREATION', 'REDEMPTION', 'HOLD_PLACED', 'HOLD_CAPTURED', 'HOLD_RELEASED')),
    amount        NUMERIC(19,2) NOT NULL,
    balance_after NUMERIC(19,2) NOT NULL,
    hold_id       BIGINT,
    created_at    TIMESTAMP NOT NULL DEFAULT now(),
    actor_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    -- The partition key (created_at) must be part of every unique/PK constraint on a partitioned
    -- table. `id` stays globally unique in practice (one shared identity sequence across partitions).
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

-- Catches every row created before this migration ran, regardless of actual historical range.
CREATE TABLE gift_card_ledger_historical PARTITION OF gift_card_ledger_new
    FOR VALUES FROM (MINVALUE) TO ('2026-01-01');

CREATE TABLE gift_card_ledger_2026 PARTITION OF gift_card_ledger_new FOR VALUES FROM ('2026-01-01') TO ('2027-01-01');
CREATE TABLE gift_card_ledger_2027 PARTITION OF gift_card_ledger_new FOR VALUES FROM ('2027-01-01') TO ('2028-01-01');
CREATE TABLE gift_card_ledger_2028 PARTITION OF gift_card_ledger_new FOR VALUES FROM ('2028-01-01') TO ('2029-01-01');
CREATE TABLE gift_card_ledger_2029 PARTITION OF gift_card_ledger_new FOR VALUES FROM ('2029-01-01') TO ('2030-01-01');

-- Safety net: a row whose created_at falls outside every range above lands here instead of failing
-- the insert outright. LedgerPartitionMonitorScheduler alerts if this ever gets rows or if fewer
-- than 12 months of dated partitions remain - both mean a follow-up migration is overdue to extend
-- the range above.
CREATE TABLE gift_card_ledger_default PARTITION OF gift_card_ledger_new DEFAULT;

-- Defined on the parent: Postgres propagates each of these to every partition automatically,
-- including ones created later.
CREATE INDEX idx_gift_card_ledger_new_giftcard_created_at ON gift_card_ledger_new (gift_card_id, created_at);
CREATE INDEX idx_gift_card_ledger_new_merchant_id ON gift_card_ledger_new (merchant_id);
CREATE INDEX idx_gift_card_ledger_new_actor_user_id ON gift_card_ledger_new (actor_user_id);

INSERT INTO gift_card_ledger_new (id, gift_card_id, merchant_id, entry_type, amount, balance_after, hold_id, created_at, actor_user_id)
    SELECT id, gift_card_id, merchant_id, entry_type, amount, balance_after, hold_id, created_at, actor_user_id
    FROM gift_card_ledger;

-- Keep the identity sequence ahead of the copied rows so future inserts don't collide with them.
SELECT setval(pg_get_serial_sequence('gift_card_ledger_new', 'id'), COALESCE((SELECT MAX(id) FROM gift_card_ledger_new), 1));

-- Privilege checks on a partitioned table happen on the table named in the query, not on the
-- individual partition a row is routed into - so the app only ever needs grants on the parent,
-- same as before. Dropping the old table frees up the original name/index/sequence names below.
DROP TABLE gift_card_ledger;

ALTER TABLE gift_card_ledger_new RENAME TO gift_card_ledger;
ALTER INDEX idx_gift_card_ledger_new_giftcard_created_at RENAME TO idx_gift_card_ledger_giftcard_created_at;
ALTER INDEX idx_gift_card_ledger_new_merchant_id RENAME TO idx_gift_card_ledger_merchant_id;
ALTER INDEX idx_gift_card_ledger_new_actor_user_id RENAME TO idx_gift_card_ledger_actor_user_id;
ALTER SEQUENCE gift_card_ledger_new_id_seq RENAME TO gift_card_ledger_id_seq;

-- V17's ALTER DEFAULT PRIVILEGES auto-grants full CRUD to p2p_app on any table the migration role
-- creates; restore the original append-only guarantee (SELECT/INSERT only) that V17 established.
REVOKE UPDATE, DELETE ON gift_card_ledger FROM p2p_app;
